### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by benio1394** [Clark919/AnimatedArmour#1]
It s not exactly an issue but when playing with frostiful mod or other mod that give temperature system it make sence. Can you make animated armor immune to freeze? Sorry if I m bothering you,

**Comment by Clark919** [comment]
Not at all! I actually had this on my to-do list since I run this Origin in my modpack which has freezing effects from staying in certain oceans for too long, which is counter-intuitive for an Origin that sinks in water in my opinion. I'll add this in the next patch.

**Comment by Clark919** [comment]
Added in the latest version (v1.5.0).
